name: Package to Executable

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.1

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r streetcatviewer/requirements.txt

      - name: Generate requirements.txt
        run: |
          poetry export --without-hashes --format=requirements.txt > streetcatviewer/requirements.txt
          
      - name: Package Program
        run: |
          pyinstaller -F streetcatviewer/main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: streetcatviewer
          path: dist/main.exe
