
name: Package to Executable

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
  
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.12.1
      - name: Install Dependences
        run: |
          python -m pip install --upgrade pip
          pip install streetcatviewer/requirements.txt
      - name: Package Program
        run: |
          pyinstaller streetcatviewer/main.py
      - name: Upload Artifact
      - uses: actions/upload-artifact@v2
        with:
          name: streetcatviewer
          path: streetcatviewer/dist/main/
          

